### ISSUE TITLE
IllegalArgumentException: Unknown call [cosineSimilarity] with [2] arguments.

### ISSUE THREAD

**Issue by covolution** [jtibshirani/text-embeddings#1]
I am running Elastic via docker: `docker.elastic.co/elasticsearch/elasticsearch:7.2.0` and get the `Unknown call [cosineSimilarity] ` error, is it something to do with x-pack?

Also, Elastic 7.2.0 or greater is required to run this because your dense vector is greater than 500 in size.  Perhaps you could add a note in the readme?

Here is the stack trace:

```elasticsearch_1  | "stacktrace": ["org.elasticsearch.transport.RemoteTransportException: [d5cf2278c164][172.19.0.2:9300][indices:data/read/search[phase/query]]",
elasticsearch_1  | "Caused by: org.elasticsearch.index.query.QueryShardException: script_score: the script could not be loaded",
elasticsearch_1  | "at org.elasticsearch.index.query.functionscore.ScriptScoreFunctionBuilder.doToFunction(ScriptScoreFunctionBuilder.java:99) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.functionscore.ScoreFunctionBuilder.toFunction(ScoreFunctionBuilder.java:143) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.functionscore.ScriptScoreQueryBuilder.doToQuery(ScriptScoreQueryBuilder.java:165) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.i....
elasticsearch_1  | "at java.lang.Thread.run(Thread.java:835) [?:?]",
elasticsearch_1  | "Caused by: org.elasticsearch.script.ScriptException: compile error",
elasticsearch_1  | "at org.elasticsearch.painless.PainlessScriptEngine.convertToScriptException(PainlessScriptEngine.java:442) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:362) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:139) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.script.ScriptService.compile(ScriptService.java:356) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.functionscore.ScriptScoreFunctionBuilder.doToFunction(ScriptScoreFunctionBuilder.java:95) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.functionscore.ScoreFunctionBuilder.toFunction(ScoreFunctionBuilder.java:143) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.functionscore.ScriptScoreQueryBuilder.doToQuery(ScriptScoreQueryBuilder.java:165) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:99) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | ....
elasticsearch_1  | "at java.lang.Thread.run(Thread.java:835) ~[?:?]",
elasticsearch_1  | "Caused by: java.lang.IllegalArgumentException: Unknown call [cosineSimilarity] with [2] arguments.",
elasticsearch_1  | "at org.elasticsearch.painless.PainlessScript$Script.compile(cosineSimilarity(params.query_vector, doc['title_vector']) + 1.0:1) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.node.ECallLocal.analyze(ECallLocal.java:108) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.node.EBinary.analyzeAdd(EBinary.java:241) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.node.EBinary.analyze(EBinary.java:77) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.node.SExpression.analyze(SExpression.java:54) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.node.SSource.analyze(SSource.java:222) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.node.SSource.analyze(SSource.java:182) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.Compiler.compile(Compiler.java:213) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.PainlessScriptEngine$2.run(PainlessScriptEngine.java:355) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.PainlessScriptEngine$2.run(PainlessScriptEngine.java:351) ~[?:?]",
elasticsearch_1  | "at java.security.AccessController.doPrivileged(AccessController.java:389) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:351) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:139) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.script.ScriptService.compile(ScriptService.java:356) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.functionscore.ScriptScoreFunctionBuilder.doToFunction(ScriptScoreFunctionBuilder.java:95) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.functionscore.ScoreFunctionBuilder.toFunction(ScoreFunctionBuilder.java:143) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.functionscore.ScriptScoreQueryBuilder.doToQuery(ScriptScoreQueryBuilder.java:165) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:99) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:293) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:305) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:292) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.parseSource(SearchService.java:743) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.createContext(SearchService.java:591) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:550) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:353) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$1(SearchService.java:340) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.action.ActionListener.lambda$map$2(ActionListener.java:145) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService$2.doRun(SearchService.java:1052) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]",
elasticsearch_1  | "at java.lang.Thread.run(Thread.java:835) ~[?:?]"] }
elasticsearch_1  | {"type": "server", "timestamp": "2019-06-27T08:10:18,092+0000", "level": "DEBUG", "component": "o.e.a.s.TransportSearchAction", "cluster.name": "text-elasticsearch", "node.name": "d5cf2278c164", "cluster.uuid": "_Oiy5WerRt6NNFP-eOqXZA", "node.id": "MpeaVJF_Q0GYQI0Xe6W92w",  "message": "All shards failed for phase: [query]" , 
elasticsearch_1  | "stacktrace": ["org.elasticsearch.script.ScriptException: compile error",
elasticsearch_1  | "at org.elasticsearch.painless.PainlessScriptEngine.convertToScriptException(PainlessScriptEngine.java:442) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:362) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:139) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.script.ScriptService.compile(ScriptService.java:356) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.functionscore.ScriptScoreFunctionBuilder.doToFunction(ScriptScoreFunctionBuilder.java:95) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.functionscore.ScoreFunctionBuilder.toFunction(ScoreFunctionBuilder.java:143) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.functionscore.ScriptScoreQueryBuilder.doToQuery(ScriptScoreQueryBuilder.java:165) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:99) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:293) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:305) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:292) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.parseSource(SearchService.java:743) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.createContext(SearchService.java:591) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:550) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:353) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$1(SearchService.java:340) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.action.ActionListener.lambda$map$2(ActionListener.java:145) ~[elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) [elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.search.SearchService$2.doRun(SearchService.java:1052) [elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758) [elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.2.0.jar:7.2.0]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
elasticsearch_1  | "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
elasticsearch_1  | "at java.lang.Thread.run(Thread.java:835) [?:?]",
elasticsearch_1  | "Caused by: java.lang.IllegalArgumentException: Unknown call [cosineSimilarity] with [2] arguments.",
elasticsearch_1  | "at org.elasticsearch.painless.PainlessScript$Script.compile(cosineSimilarity(params.query_vector, doc['title_vector']) + 1.0:1) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.node.ECallLocal.analyze(ECallLocal.java:108) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.node.EBinary.analyzeAdd(EBinary.java:241) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.node.EBinary.analyze(EBinary.java:77) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.node.SExpression.analyze(SExpression.java:54) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.node.SSource.analyze(SSource.java:222) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.node.SSource.analyze(SSource.java:182) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.Compiler.compile(Compiler.java:213) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.painless.PainlessScriptEngine$2.run(PainlessScriptEngine.java:355) ~[?:?]",
```

**Comment by jtibshirani** [comment]
Hi @covolution, thanks for filing this and my apologies for initially missing it. The vector functions were only released in Elasticsearch 7.3, and are not available in 7.2. I updated the README in https://github.com/jtibshirani/text-embeddings/commit/b96666af0bacd075ccc61af9f9a09dbc9d2c8205 to specify that Elasticsearch 7.3 is required, and that the cluster must be running with the default distribution (not pure OSS).
